[package]
name = "uniflow-models"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
regex.workspace = true
serde.workspace = true
uniflow-hir = { path = "../hir" }
uniflow-rules = { path = "../rules" }
serde_yaml.workspace = true
zhhz.workspace = true

[dev-dependencies]
regex-syntax.workspace = true
uniflow-baseline = { path = "../baseline" }
