[package]
name = "uniflow-lang-javascript"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
oxc_allocator.workspace = true
oxc_ast.workspace = true
oxc_parser.workspace = true
oxc_span.workspace = true
oxc_syntax.workspace = true
uniflow-hir = { path = "../hir" }
uniflow-parser-core = { path = "../parser_core" }
