[package]
name = "uniflow-report"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
uniflow-taint = { path = "../taint" }
uniflow-value-flow = { path = "../value_flow" }
uniflow-checker-api = { path = "../checker_api" }
