[package]
name = "uniflow-value-flow"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
experimental-advanced-value-flow = [
    "uniflow-lang-python/experimental-python-semantics",
    "uniflow-lowering/experimental-python-semantics",
]

[dependencies]
petgraph.workspace = true
serde.workspace = true
uniflow-hir = { path = "../hir" }
uniflow-ir = { path = "../ir" }
uniflow-rules = { path = "../rules" }

[dev-dependencies]
uniflow-lang-cpp = { path = "../lang_cpp" }
uniflow-lang-java = { path = "../lang_java" }
uniflow-parser-core = { path = "../parser_core" }
uniflow-lang-python = { path = "../lang_python" }
uniflow-lowering = { path = "../lowering" }
