[package]
name = "uniflow-lowering"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
experimental-python-semantics = ["uniflow-lang-python/experimental-python-semantics"]

[dependencies]
indexmap.workspace = true
uniflow-hir = { path = "../hir" }
uniflow-ir = { path = "../ir" }

[dev-dependencies]
uniflow-lang-c = { path = "../lang_c" }
uniflow-lang-cpp = { path = "../lang_cpp" }
uniflow-lang-java = { path = "../lang_java" }
uniflow-lang-frontends = { path = "../lang_frontends" }
uniflow-lang-python = { path = "../lang_python" }
uniflow-parser-core = { path = "../parser_core" }
