[package]
name = "uniflow-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
default-run = "uniflow"

[[bin]]
name = "uniflow"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
indicatif.workspace = true
serde.workspace = true
serde_json.workspace = true
uniflow-cache = { path = "../cache" }
uniflow-frontend = { path = "../frontend" }
uniflow-hir = { path = "../hir" }
uniflow-ir = { path = "../ir" }
uniflow-lowering = { path = "../lowering" }
uniflow-models = { path = "../models" }
uniflow-rules = { path = "../rules" }
uniflow-report = { path = "../report" }
uniflow-taint = { path = "../taint" }
uniflow-value-flow = { path = "../value_flow" }
uniflow-platform = { path = "../platform" }
serde_yaml.workspace = true
uniflow-baseline = { path = "../baseline" }
uniflow-checker-api = { path = "../checker_api" }
uniflow-checker-host = { path = "../checker_host" }

[dev-dependencies]
regex-syntax.workspace = true
