[package]
name = "uniflow-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
indicatif.workspace = true
serde_json.workspace = true
uniflow-cache = { path = "../cache" }
uniflow-frontend = { path = "../frontend" }
uniflow-hir = { path = "../hir" }
uniflow-ir = { path = "../ir" }
uniflow-lowering = { path = "../lowering" }
uniflow-models = { path = "../models" }
uniflow-rules = { path = "../rules" }
uniflow-report = { path = "../report" }
uniflow-taint = { path = "../taint" }
uniflow-value-flow = { path = "../value_flow" }
