[package]
name = "uniflow-rules"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
regex.workspace = true
regex-syntax.workspace = true
serde.workspace = true
serde_yaml.workspace = true
uniflow-hir = { path = "../hir" }
