[package]
name = "uniflow-lang-dotnet-bytecode"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
indexmap.workspace = true
dotnetdll.workspace = true
uniflow-hir = { path = "../hir" }
uniflow-ir = { path = "../ir" }
