[package]
name = "uniflow-sca-reachability"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
rayon.workspace = true
walkdir = "2"
regex.workspace = true
zip.workspace = true
uniflow-hir = { path = "../hir" }
uniflow-frontend = { path = "../frontend" }
uniflow-sca-core = { path = "../sca_core" }

[dev-dependencies]
tempfile = "3.27"
