id: io.quarkus.quarkus-resteasy-deployment
language: Java
message: pkg:maven/io.quarkus/quarkus-resteasy-deployment
metadata:
  purl: pkg:maven/io.quarkus/quarkus-resteasy-deployment
rule:
  inside:
    kind: import_declaration
  kind: scoped_identifier
  regex: ^(io\.quarkus\.resteasy\.deployment)\.
